name: flutter_application_commerce
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  carousel_pro: ^1.0.0
  firebase_auth: ^3.3.8
  cloud_firestore: ^3.1.9
  google_sign_in: ^5.4.1
  shared_preferences: ^2.0.13
  fluttertoast: ^8.0.9
  firebase_database: ^9.0.8
  flutter_signin_button: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
   - images/
   - images/Start_page_pic1.jpg
   - images/Start_page_pic.jpg 
   - images/pic1.jpg
   - images/Login1.jpg
   - images/Log1.jpg
   - images/Log2.png
   - images/Login2.jpg
   - images/products/blazer1.jpeg
   - images/products/blazer2.jpeg
   - images/products/dress1.jpeg
   - images/products/dress2.jpeg
   - images/products/hills1.jpeg
   - images/products/hills2.jpeg
   - images/products/pants1.jpg
   - images/products/pants2.jpeg
   - images/products/shoe1.jpg
   - images/products/skt1.jpeg
   - images/products/skt2.jpeg
   - images/c1.jpg
   - images/google_icon.png
   - images/images.jpeg
   - images/images1.jpeg
   - images/images2.jpeg
   - images/images3.jpeg
   - images/images7.jpg
   - images/images8.jpg
   - images/images9.jpg
   - images/images10.jpg
   - images/images11.jpg
   - images/p.png
   - images/w1.jpeg
   - images/w3.jpeg
   - images/w4.jpeg
   - images/cats/accessories.png
   - images/cats/dress.png
   - images/cats/formal.png
   - images/cats/informal.png
   - images/cats/jeans.png
   - images/cats/shoe.png
   - images/cats/tshirt.png
   
   - images/Icon_blazer.png
   - images/Icon_dress.png
   - images/Icon_shirt2.png
   - images/Icon_short.png
   - images/Icon_sweater2.png
   - images/Icon_tie.png
   - images/Icon_skirt2.png
   - images/Icon_socks2.png
   - images/Icon_pants2.png

   - images/blazer.jpg
   - images/dress.jpg
   - images/Shirt1.jpg
   - images/short.jpg
   - images/Skirt.png
   - images/Sweater.jpg
   - images/Tie2.jpg
   - images/Trouser.jpg



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
